### ISSUE TITLE
cant get self casting to work

### ISSUE THREAD

**Issue by FireCulex** [loopuleasa/Dota2-TheCore-Config-Engine#108]
double tap is enabled, but i have to select the item and then mouseover my hero for it to work, as opposed to quickly double tapping. gets me killed quite a bit.

**Comment by jaccarmac** [comment]
In this layout, self-cast is bound to ALT + *key* by default, not double tap *key*.

**Comment by FireCulex** [comment]
That did it thanks. Sounds like a great FAQ question :D
