### ISSUE TITLE
Option for AutoCast

### ISSUE THREAD

**Issue by abhinav91690** [loopuleasa/Dota2-TheCore-Config-Engine#110]
Is there an option for setting a spell to AutoCast?
Anyway to add autocast to the ALT + SPACE toggle ?

**Comment by dvinesett** [comment]
Off the top of my head, ALT+Z or SPACE+Z, but I am on an older version

**Comment by dvinesett** [comment]
no hero has more than one autocast afaik so the bind just tries them all

**Comment by dodekeract** [comment]
I know it's not the same, but you should be able to use CTRL and click the skill you want to toggle.

**Comment by dvinesett** [comment]
Correct me if I'm wrong, but no hero has more than one auto-castable spell. However, I see how this may be a problem with custom games

**Comment by abhinav91690** [comment]
I just tried these. They didnt work.

ALT + SPACE only toggles quick cast and normal cast.
ALT + W gives normal cast
CLT + W says no points left to upgrade

There is no way to select a spell to auto cast.
Really frustrating when u play silencer .

**Comment by dvinesett** [comment]
Try SPACE + Z. [Source as reference](https://github.com/loopuleasa/Dota2-TheCore-Config-Engine/blob/master/Dota%202%20Reborn%20Keyboard%20Setups/Loopuleasa's%20Super%20Compact%20QWERTG-DFXCV%20layout%20(ALT%2CSPACE%20mods)/dota2_gameplay_mode/dota2_keybinds_space_pressed.cfg#L116)

**Comment by loopuleasa** [comment]
It's implemented and bound to SPACE+Z
