### ISSUE TITLE
"quick_upgrade_courier" alias does not upgrade courier.

### ISSUE THREAD

**Issue by elnoss** [loopuleasa/Dota2-TheCore-Config-Engine#119]
`quick_upgrade_courier` defined in `dota2_gameplay_mode/aliases/dota2_functions_active.cfg` does not upgrade courier as of 6.86. It instead purchases a new walking courier. This is because of the newly introduced Faerie Fire item which pushes Flying Courier down a row. Should be a pretty quick fix.

**Comment by loopuleasa** [comment]
Good spot.
I had this issue in the past when mango was added.
