### ISSUE TITLE
Need Help with camera and few issues and commands

### ISSUE THREAD

**Issue by queenofpains** [loopuleasa/Dota2-TheCore-Config-Engine#123]
* **Jump camera option**

>We have an option to jump to a "Hero" ( "Select hero" ) with this command

>alias "+tohero" "+dota_camera_follow;-dota_camera_follow;+dota_camera_follow"
bind "1" "+tohero"  

>I was wondering if there is an option to jump the camera to the location of "other Selected other Units" 
( "Select other units" )

* **New commands added to cfg dont work unless i manually load it using the console or bind a button to load a cfg** 

* **is there a way i can  use the midas sound to make sure the cfg is automticaly loaded when i join a game or go into the game ( after the pick phase ) and is it also possible for me to add the midas sound when  i use a key to bind a cfg ?**

_NOTE Im just using bits and parts of ur cfg since Im not much into modifiers. Thanks_

**Comment by dodekeract** [comment]
You could try this `bind 2 "dota_select_all_others;dota_select_all_others"`.

**Comment by queenofpains** [comment]
any idea about the other two issues ?

**Comment by dodekeract** [comment]
Well, I could probably help you, but github issues are such a slow way to communicate. Add me on steam: http://steamcommunity.com/id/dodekeract.

**Comment by queenofpains** [comment]
added you thanks

**Comment by queenofpains** [comment]
add me and drop me a message . Im gonna hit the bed . good night
