### ISSUE TITLE
Binding for G doesn't work correctly

### ISSUE THREAD

**Issue by EddyTheTeddy** [loopuleasa/Dota2-TheCore-Config-Engine#127]
Hello,

my G-key isn't bound correctly for some reason. All other skills and items don't show the key that needs to be pressed, except for Subskill 2 (Skill 4), it shows G. This wouldn't be a problem, but as a result, selfcast doesn't work and if I rebind keys for Invoker (I swap D and F for T and G), then it still shows G for Subskill 2 and I can't use the item in slot 3.

I don't know how to solve this problem, seeing as in the configs, everything looks the same for G as it does for all the other keys and they work just fine...

If you need any cfg-files or more information, just let me know! Thanks in advance!

**Comment by dodekeract** [comment]
You most likely set G in "autocast" or "selfcast" or "quickcast" for that spell. Try to remove that. Also why did you close this issue?
