### ISSUE TITLE
Help needed

### ISSUE THREAD

**Issue by dreodahl** [loopuleasa/Dota2-TheCore-Config-Engine#147]
I can't get the Loopuleasa's Super Compact QWERTG-DFXCV keyboard script to work. I have removed all in-game keybinds, downloaded the archive, extracted it, and put all the files inside the "Loopuleasa's Super Compact QWERTG-DFXCV layout (ALT,SPACE mods)" folder into Steam\steamapps\common\dota 2 beta\game\dota\cfg. If anyone could help me, that would be great :)

**Comment by dodekeract** [comment]
Open console, enter `exec autoexec.cfg`.

**Comment by dreodahl** [comment]
I've already done that :(

**Comment by dodekeract** [comment]
No errors?

**Comment by kingalca** [comment]
Did you have heard an Midas Usage Sound? If so, the config has been loaded. It gives ingame text based and audio feedback, no onscreen text (besides the to-Coach-Chat lines).

**Comment by dreodahl** [comment]
There was no sound and no in-game feedback. I have -console -autoexec.cfg in the launch options and here's a screenshot of the local files: 
![currentfiles](https://cloud.githubusercontent.com/assets/18188900/14202872/6e5bfca8-f7f2-11e5-8087-05981f5ab185.png)

**Comment by dreodahl** [comment]
I also tried only having the contents of the folders you see here in the cfg file, but that didn't work so I did this. I don't know what I'm doing wrong. Please help me :p

**Comment by dodekeract** [comment]
You put the files in the wrong folder.

**Comment by dreodahl** [comment]
I put the files in \Steam\SteamApps\common\dota 2 beta\game\dota\cfg\. This is what the guide says to do. Could you elaborate please?

**Comment by dodekeract** [comment]
Judging from your screenshot, you didn't.

**Comment by dreodahl** [comment]
The file path is the same. \Steam\SteamApps\common\dota 2 beta\game\dota\cfg is identical to \Steam\SteamApps\common\dota 2 beta\game\dota\cfg.

**Comment by dodekeract** [comment]
Where do you see the \game\ folder in the screenshot? I can't see it. Weird...

**Comment by dreodahl** [comment]
I see what's happened. I have been looking at multiple READMEs and one of them says: 2. Choose one of the keyboard layouts in the various folders you see here and copy the contents to \Steam\SteamApps\common\dota 2 beta\dota\cfg\ (Look in the "keyboard layout visual images" folder to see how the layout will be). I will try the new file path.

**Comment by AetherV** [comment]
Wait isn't that the Pre reborn folder o.O guess there's a readme that needs to be fixed.

**Comment by dodekeract** [comment]
That's because that is the source 1 DotA autoexec path and your other source was probably not updated. Weird nevertheless to claim multiple times that you pasted it to a different folder though.

**Comment by AetherV** [comment]
Yeah also wierd cause you got it right in your initial post but not the subsequent ones

**Comment by dreodahl** [comment]
I obviously put it in the wrong path. Calm yourselves.

**Comment by dreodahl** [comment]
It seems to be working now. Thanks for the help.

**Comment by dodekeract** [comment]
You are the on who implies I can't read a path shown in a screenshot. Also you didn't close the issue, even though it is resolved.
