### ISSUE TITLE
How do I move the camera?

### ISSUE THREAD

**Issue by nightieRB** [loopuleasa/Dota2-TheCore-Config-Engine#157]
Is there any way to do it apart from mouse - wall bump? I'm used to WASD movement and I'd like something that'd keep mouse near the center of my screen? I remember in an earlier version that you could middle click and drag but that doesn't seem to work. Halp?

**Comment by AetherV** [comment]
Update your configuration. Middle mouse was fixed if you update (also comes with some other goodies you might want to check out too), the spring cleaning update broke it for the old versions.
 Wasd movement is not possible, since they are bound. You have the choice of rewriting the configuration or using the manta config engine for advanced customization. 

---- nightieRB wrote ----

**Comment by nightieRB** [comment]
Oki, I'll check reddit. Thanks!

**Comment by AetherV** [comment]
No not reddit,  the github directly. You can download the master branch containing all of the updates from github (reddit is going to refer you here anyways).

---- nightieRB wrote ----

**Comment by nightieRB** [comment]
Aha, I'll look around my I have the brain power of Roshan. Can you post a direct link?

**Comment by nightieRB** [comment]
Also, do I just paste it in where it should go and click replace for all or is there something else I need to do?

**Comment by AetherV** [comment]
https://github.com/loopuleasa/Dota2-TheCore-Config-Engine

And download zip

---- nightieRB wrote ----

**Comment by AetherV** [comment]
Note: only the standard configuration (read not iso, not German) configuration works. Just take the standard configuration folder and replace it with your current files (overwrite). Probably the easiest way.

Basically follow step 3 of the readme 

---- nightieRB wrote ----

**Comment by nightieRB** [comment]
Ok, I'm getting a file cannot exceed 260 character limit error

**Comment by AetherV** [comment]
From what?

---- nightieRB wrote ----

**Comment by nightieRB** [comment]
Extracting it into a folder. Get a bunch of those from WinRAR. It seems to be completely untouched though

**Comment by nightieRB** [comment]
Also, I can't read MD files but I'm assuming you just mean copy the stuff from the Loopuleasa's Super Compact QWERTG-DFXCV layout (ALT,SPACE mods) into where they're meant to go.

**Comment by AetherV** [comment]
Yeah that's what I meant. You open MD files with notepad or notepad++. I think wordpad supports it  to.


---- nightieRB wrote ----

**Comment by nightieRB** [comment]
Got coin sounds
Middle mouse doesn't work to grip :/ (unless I'm doing it wrong)
I assume then, that the config is with mouse-edge bumping?

**Comment by nightieRB** [comment]
Not working, can't use my abilities. Halp?

**Comment by nightieRB** [comment]
Says it's unbound? Did I do something wrong?

**Comment by nightieRB** [comment]
I think it's because I don't have the core installed.

**Comment by AetherV** [comment]
no you don't need the core, send me an image of your file structure at the cfg folder (just open the folder in Explorer and Screenshot it). Second, find this file: dota2_keybinds_alt_pressed.cfg and upload it to pastebin or something similar. 

---- nightieRB wrote ----

**Comment by nightieRB** [comment]
Okay, I've copied in so much shit I wouldn't be surprised if I broke something. Working on it now.

**Comment by nightieRB** [comment]
File structure: http://prntscr.com/b6zn5x
Dota2_keybinds_alt_pressed.cfg: http://pastebin.com/xzTC5Ny5

**Comment by AetherV** [comment]
did you install the core, because you got some strange files that aren't supposed to be there. The core is pretty broken and not intended for use (most fixes are done to loops configuration.

---- nightieRB wrote ----

**Comment by AetherV** [comment]
I can post a detailed instruction guide later this afternoon (2-3 hours) when I get back on a PC since I'm currently not at home. It'll come with a Deinstallation guide. (need to overhaul the readme anyways)

---- nightieRB wrote ----

**Comment by nightieRB** [comment]
Alright that's great because I've got so much stuff there I need someone to tell me how to go clean again.

**Comment by dodekeract** [comment]
@nightieRB backup your config folder and then delete it. If something breaks, just restore the backup.

**Comment by nightieRB** [comment]
config as in cfg or config as in config

**Comment by AetherV** [comment]
there are two files that you require, otherwise dota2 breaks (from my experience). The problem simply is I got no idea which two files it was.

**Comment by nightieRB** [comment]
I assume I need a backup of cfg.
I don't have that but I'll try find it on the internet.

**Comment by AetherV** [comment]
Alright, sorry, turns out I had a lot more to do today than I originally anticipated.

Delete everything but `user_keys_default.vcfg`.
**Very Important:** Do not confuse the file with `user_keys_dev_default.vcfg`

Then add all the files in the folder `Loopuleasa's Super Compact QWERTG-DFXCV layout (ALT,SPACE mods)` into `C:\Program Files (x86)\Steam\steamapps\common\dota 2 beta\game\dota\cfg` (or wherever dota is installed).

This should give you a fresh install.

**Comment by nightieRB** [comment]
Did it, will check later. Thanks a lot.
