### ISSUE TITLE
sixense_left_click command does not work on Mac and Linux versions of Dota 2 and Source 2

### ISSUE THREAD

**Issue by hugomg** [loopuleasa/Dota2-TheCore-Config-Engine#3]
The +sixense_left_click command and other "sixense" commands are only available in Windows and some keybinds, like "quick attack" and "quick follow" don't work on Mac and Linux.

Making a new version of the .cfg files jsut for Mac/Linux might be too much trouble but I think a simple warning on the Readme might already be helpful.

**Comment by loopuleasa** [comment]
VOLVO PLEASE ADD A LEFT CLICK FOR US

PLEASE

**Comment by loopuleasa** [comment]
anyone know how we can get in contact with valve devs on a dev forum or something?

**Comment by SkipKayhil** [comment]
In case you hadn't found this yet: http://dev.dota2.com/forumdisplay.php?f=475

**Comment by loopuleasa** [comment]
These do not apply to Reborn, which is the main supported version, so I will close this thread.
