### ISSUE TITLE
Hero Specific Setup

### ISSUE THREAD

**Issue by shauder** [loopuleasa/Dota2-TheCore-Config-Engine#30]
You forgot to change the execif to exec in the hero setups.

I also like to add the nohero_mode to the autoexec.cfg otherwise u get an error in console complaining about load_current_hero_nomod_binds not being found until you launch that command or another hero.

**Comment by loopuleasa** [comment]
I can fix these fast sure.

**Comment by loopuleasa** [comment]
fixed these
