### ISSUE TITLE
[Legacy] F7 does not properly switch between quick cast and normal cast.

### ISSUE THREAD

**Issue by joshjayk** [loopuleasa/Dota2-TheCore-Config-Engine#35]
When I hit F7 to switch from the default (quick cast) to normal cast, it still quick casts everything. I've found that I can fix this by first self-casting a spell or an item, but I'd rather not have to do that every time I play.

Is there a way I can just completely disable quick cast from being a function?

Thanks for the otherwise awesome layout!

**Comment by loopuleasa** [comment]
I will look into it when I find some time

**Comment by joshjayk** [comment]
Also, I'm not sure how to switch quick attack move to just normal attack move. F7 didn't seem to be doing it.

Thanks!

**Comment by loopuleasa** [comment]
That doesn't affect the attack/follow commands

maybe it should

**Comment by loopuleasa** [comment]
fixed it and I will add it to main soon
