### ISSUE TITLE
Keyboard Visual Images are out of date

### ISSUE THREAD

**Issue by loopuleasa** [loopuleasa/Dota2-TheCore-Config-Engine#43]
Some might need an update with recent changes.

**Comment by Sembrani** [comment]
Working on it now; [Current State](http://www.keyboard-layout-editor.com/##@_backcolor=%23222222%3B&@_c=%23d89793&t=%23253928&p=DCS%3B&=Cancel%20Select%0A%0A%0A%0AEsc&_x:1&c=%23aaaaaa&t=%23282828%3B&=Rune%20Check%20Shuffle%0A%0A%0A%0AF1&_c=%23044bd0&t=%23e3e5d8%3B&=Select%20Courior%0A%0A%0A%0AF2&=Courior%20Deliver%20Items%0A%0A%0A%0AF3&=Quick%20Buy%0A%0A%0A%0AF4&_x:0.5&c=%23514a38&t=%23aaaaaa%3B&=Toggle%20Game%20Menu%0A%0A%0A%0AF5&=Toggle%20Combat%20Log%0A%0A%0A%0AF6&_c=%2365af4c&t=%231d3327%3B&=Cast%20Mode%20Toggle%0A%0A%0A%0AF7&_c=%23514a38&t=%23aaaaaa%3B&=Reload%20Config%20Files%0A%0A%0A%0AF8&_x:0.5&c=%23c9c2b0&t=%231d3327%3B&=Pause%20Game%0A%0A%0A%0AF9&_c=%23d89793&t=%23253928%3B&=Toggle%20Select%20Summon%0A%0A%0A%0AF10&_c=%23514a38&t=%23aaaaaa%3B&=Toggle%20Dev%20Mode%0A%0A%0A%0AF11&=Take%20Screen%20shot%0A%0A%0A%0AF12&_x:0.5&c=%23282828%3B&=%0A%0A%0A%0APrtScr&=%0A%0A%0A%0AS.Lock&=%0A%0A%0A%0APause%0ABreak%3B&@_y:0.5&c=%23ff8000&t=%23282828&a:0%3B&=Ping%20(New%20Alt)%0A%0A%0A%0A%2F&nbsp%2F%3B~%0A%60%2F&nbsp%2F%3B&_c=%23d89793&t=%23253928%3B&=Select%20Hero%0A%0A%0A%0A%2F&nbsp%2F%3B!%0A1%2F&nbsp%2F%3B&=Control%20Group%201%0A%0A%0A%0A%2F&nbsp%2F%3B%2F@%0A2%2F&nbsp%2F%3B&_a:2%3B&=Control%20Group%202%0A%0A%0A%0A%2F&nbsp%2F%3B%23%0A3%2F&nbsp%2F%3B&=Control%20Group%203%0A%0A%0A%0A%2F&nbsp%2F%3B$%0A4%2F&nbsp%2F%3B&_a:0%3B&=Control%20Group%204%0A%0A%0A%0A%2F&nbsp%2F%3B%25%0A5%2F&nbsp%2F%3B&=Control%20Group%205%0A%0A%0A%0A%2F&nbsp%2F%3B%5E%0A6%2F&nbsp%2F%3B&=Control%20Group%206%0A%0A%0A%0A%2F&nbsp%2F%3B%2F&%0A7%2F&nbsp%2F%3B&=Control%20Group%207%0A%0A%0A%0A%2F&nbsp%2F%3B*%0A8%2F&nbsp%2F%3B&=Control%20Group%208%0A%0A%0A%0A%2F&nbsp%2F%3B(%0A9%2F&nbsp%2F%3B&=Control%20Group%209%0A%0A%0A%0A%2F&nbsp%2F%3B)%0A0%2F&nbsp%2F%3B&_c=%23282828&t=%23aaaaaa%3B&=%0A%0A%0A%0A%2F&nbsp%2F%3B%2F_%0A-%2F&nbsp%2F%3B&=%0A%0A%0A%0A%2F&nbsp%2F%3B+%0A%2F=%2F&nbsp%2F%3B&_a:4&w:2%3B&=%0A%0A%0A%0ABackspace&_x:0.5%3B&=%0A%0A%0A%0AInsert&=%0A%0A%0A%0AHome&=%0A%0A%0A%0APgUp&_x:0.5%3B&=%0A%0A%0A%0AN.Lock&=%0A%0A%0A%0A%2F%2F&=%0A%0A%0A%0A*&=%0A%0A%0A%0A-%3B&@_c=%23d89793&t=%23253928&w:1.5%3B&=Cycle%20Control%20Groups%0A%0A%0A%0ATab&_c=%2365af4c&t=%231d3327&a:5%3B&=Quick%20Ability%201%0A%0A%0A%0AQ&=Quick%20Ability%202%0A%0A%0A%0AW&=Quick%20Ability%203%0A%0A%0A%0AE&=Quick%20Ability%204%0A%0A%0A%0AR&=Quick%20Sub%20Ab.%201%0A%0A%0A%0AT&_c=%23058550&t=%23ced1e4&a:4%3B&=Ability%20Learn%20Mode%0A%0A%0A%0AY&_c=%23ee4942&t=%23253928%3B&=Toggle%20Right.C%20Deny%0A%0A%0A%0AU&_c=%23aaaaaa&t=%23282828%3B&=Inspect%20Hero%0A%0A%0A%0AI&_c=%23ee4942&t=%23253928%3B&=Right.C%20Deny%20On%0A%0A%0A%0AO&_c=%23282828&t=%23aaaaaa%3B&=%0A%0A%0A%0AP&_c=%23fde731&t=%231d3327&a:0%3B&=Action%20Item%0A%0A%0A%0A%2F&nbsp%2F%3B%7B%0A%5B%2F&nbsp%2F%3B&=Taunt%20Item%0A%0A%0A%0A%2F&nbsp%2F%3B%7D%0A%5D%2F&nbsp%2F%3B&_c=%23514a38&t=%23aaaaaa&a:3&w:1.5%3B&=Console%0A%0A%0A%0A%2F&nbsp%2F%3B%2F&nbsp%2F%3B%2F&nbsp%2F%3B%2F&nbsp%2F%3B%2F&nbsp%2F%3B%7C%0A%5C%2F&nbsp%2F%3B%2F&nbsp%2F%3B%2F&nbsp%2F%3B%2F&nbsp%2F%3B%2F&nbsp%2F%3B&_x:0.5&c=%23282828&a:4%3B&=%0A%0A%0A%0ADelete&=%0A%0A%0A%0AEnd&=%0A%0A%0A%0APgDn&_x:0.5&a:0%3B&=%0A%0A%0A%0A7%0AHome&_c=%23aaaaaa&t=%23282828%3B&=Camera%20Up%0A%0A%0A%0A8%0A%E2%86%91&_c=%23282828&t=%23aaaaaa%3B&=%0A%0A%0A%0A9%0APgUp&_a:4&h:2%3B&=%0A%0A%0A%0A+%3B&@_c=%23ff8000&t=%23282828&w:1.75%3B&=Voice%20Chat%20Push-to-Talk%0A%0A%0A%0ACaps%20Lock&_c=%23ee4942&t=%23253928%3B&=Quick%20Attack-move%0A%0A%0A%0AA&=Stop%0A%0A%0A%0AS&_c=%23008dea&t=%231d3327%3B&=Quick%20Item%202%0A%0A%0A%0AD&=Quick%20Item%203%0A%0A%0A%0AF&_c=%2365af4c%3B&=Quick%20Sub%20Ab.%202%0A%0A%0A%0AG&_c=%23058550&t=%23ced1e4%3B&=Learn%20Stats%0A%0A%0A%0AH&_c=%23ff8000&t=%23282828%3B&=%22Miss%20Top%22%0A%0A%0A%0AJ&=%22Miss%20Middle%22%0A%0A%0A%0AK&=%22Miss%20Bot%22%0A%0A%0A%0AL&_c=%23282828&t=%23aaaaaa&a:0%3B&=%0A%0A%0A%0A%2F&nbsp%2F%3B%2F:%0A%2F%3B%2F&nbsp%2F%3B&=%0A%0A%0A%0A%2F&nbsp%2F%3B%22%0A'%2F&nbsp%2F%3B&_c=%23ff8000&t=%23282828&a:4&w:2.25%3B&=Say%20Team%0A%0A%0A%0AEnter&_x:4&c=%23aaaaaa&a:0%3B&=Camera%20Left%0A%0A%0A%0A4%0A%E2%86%90&=Camera%20Grip%0A%0A%0A%0A5&=Camera%20Right%0A%0A%0A%0A6%0A%E2%86%92%3B&@_c=%23808000&t=%23d9dce1&a:4&w:1.75&w2:2.25%3B&=Queue%20Command%20Modifier%0A%0A%0A%0AShift&_x:0.5&c=%23aaaaaa&t=%23282828%3B&=Jump%20Recent%20Ping%0A%0A%0A%0AZ&_c=%23008dea&t=%231d3327%3B&=Quick%20Item%204%0A%0A%0A%0AX&=Quick%20Item%205%0A%0A%0A%0AC&=Quick%20Item%206%0A%0A%0A%0AV&_c=%23044bd0&t=%23e3e5d8%3B&=Toggle%20Shop%0A%0A%0A%0AB&_c=%23ff8000&t=%23282828%3B&=%22I'm%20Back%22%0A%0A%0A%0AN&=%22Enemy%20Return%22%0A%0A%0A%0AM&_a:0%3B&=%22All%20Miss%22%0A%0A%0A%0A%2F&nbsp%2F%3B%3C%0A,%2F&nbsp%2F%3B&_c=%23282828&t=%23aaaaaa%3B&=%0A%0A%0A%0A%2F&nbsp%2F%3B%3E%0A.%2F&nbsp%2F%3B&=%0A%0A%0A%0A%2F&nbsp%2F%3B%3F%0A%2F%2F%2F&nbsp%2F%3B&_a:4&w:2.75%3B&=%0A%0A%0A%0AShift&_x:1.5%3B&=%0A%0A%0A%0A%E2%86%91&_x:1.5&a:0%3B&=%0A%0A%0A%0A1%0AEnd&_c=%23aaaaaa&t=%23282828%3B&=Camera%20Down%0A%0A%0A%0A2%0A%E2%86%93&_c=%23282828&t=%23aaaaaa%3B&=%0A%0A%0A%0A3%0APgDn&_c=%23ff8000&t=%23282828&a:4&h:2%3B&=Say%20Team%0A%0A%0A%0AEnter%3B&@_c=%23808000&t=%23d9dce1&w2:1.25%3B&=Unified%20Command%20Modifier%0A%0A%0A%0ACtrl&_x:0.25&c=%23282828&t=%23aaaaaa&w:1.25%3B&=%0A%0A%0A%0AWin&_c=%239623fe&t=%23d9dce1&w:1.25%3B&=Alt%20Modifier%0A%0A%0A%0AAlt&_c=%231f0051&t=%23f7f4e6&p=DCS%20SPACE&a:7&w:6.25%3B&=Space%20Modifier&_c=%239623fe&t=%23d9dce1&p=DCS&a:4&w:1.25%3B&=Alt%20Modifier%0A%0A%0A%0AAlt&_c=%23282828&t=%23aaaaaa&w:1.25%3B&=%0A%0A%0A%0AWin&_w:1.25%3B&=%0A%0A%0A%0AMenu&_w:1.25%3B&=%0A%0A%0A%0ACtrl&_x:0.5%3B&=%0A%0A%0A%0A%E2%86%90&=%0A%0A%0A%0A%E2%86%93&=%0A%0A%0A%0A%E2%86%92&_x:0.5&a:0&w:2%3B&=%0A%0A%0A%0A%2F&nbsp%2F%3B%2F&nbsp%2F%3B%2F&nbsp%2F%3B%2F&nbsp%2F%3B%2F&nbsp%2F%3B0%0AIns%2F&nbsp%2F%3B%2F&nbsp%2F%3B%2F&nbsp%2F%3B%2F&nbsp%2F%3B%2F&nbsp%2F%3B&=%0A%0A%0A%0A%2F&nbsp%2F%3B.%0ADel%2F&nbsp%2F)

**Comment by loopuleasa** [comment]
awesome job

those links are too big to show in mozilla, only works in chrome

**Comment by Sembrani** [comment]
Issue can be closed now?

**Comment by loopuleasa** [comment]
ofc
