### ISSUE TITLE
Remap alt key doesnt work in german layout

### ISSUE THREAD

**Issue by Kabushiki** [loopuleasa/Dota2-TheCore-Config-Engine#49]
dota_remap_alt_key "^" 

This doesn't work. Other keys like "." work but this one doesn't for some reason.

**Comment by loopuleasa** [comment]
It's probably not a supported key for that command.

**Comment by lawli3t** [comment]
I have binded the hero-center button on circumflex. but you cant use circumflex in the config, you have to use \

try dota_remap_alt_key "\" - im not sure if it will work, but you can try

**Comment by loopuleasa** [comment]
Try to look into the german layouts ported by our contributor, and see if those work.
