### ISSUE TITLE
Some Abilities / Items Quick-cast, some not

### ISSUE THREAD

**Issue by Sembrani** [loopuleasa/Dota2-TheCore-Config-Engine#52]
Mentioned in Issue #26, Comment 3, You want some abilities and items quick casted, and some not. I assume you want this as a toggle? (i.e. press Alt+abilitykey to toggle between the two modes for each skill/item)

I am happy to start working on this, as I have quite a bit of free time at the moment.

**Comment by loopuleasa** [comment]
Yep, that is a functionality I wanted to do, but I am unsure how to enable something like that.

Ideally, I would like an extra modifier key that does that (Like your press U+Key to change that key to be reversed cast)

**Comment by SkipKayhil** [comment]
You could even re-purpose F7 since that is the current key to toggle them all

**Comment by Sembrani** [comment]
My line of thought was to swap Alt and Space (so space became self-cast), and re-purpose the alt modifier as the individual toggle, but I can see the advantages of that. Could I use Alt+Space as a third modifier to swap them?

**Comment by Sembrani** [comment]
Ok. The underlying scripts should work now, I just need a modifier that we can use for this,  then I can test it and put a pull request in.

**Comment by Sembrani** [comment]
@SkipKayhil I've rewritten the F7 script so that it will force all hotkeys to be quick-cast or normal cast, cycling between them.

**Comment by loopuleasa** [comment]
> Could I use Alt+Space as a third modifier to swap them?

Yes please

And yeah, generalising the script to have PER key toggles, can do wonders. This effort should make something really great.
I saw players like sing sing go into settings at game start to change like meepo poof to be quick cast.

**Comment by Sembrani** [comment]
Can be closed now?
