### ISSUE TITLE
Remapped Ping (Tilde) stopped working

### ISSUE THREAD

**Issue by HASJ** [loopuleasa/Dota2-TheCore-Config-Engine#57]
I even reinstalled dota 2 (deleted the folder even) but it stopped working and only works when the cfgs aren't being executed.
I can't ping but everything else that does not use the Tilde key (Ability warn, How much gold to item, Buyback info, etc.) works.
I use an ABNT keyboard, which means the "~" key, is actually an apostrophe (' key). I'm reporting it only now because the cfgs worked wonderfully, until now.
Tested on Reborn.

**Comment by loopuleasa** [comment]
Apparently the dota_remap_alt command doesn't support some keys 

more people reported that to me

**Comment by loopuleasa** [comment]
It's probably something that valve did with the recent updates

**Comment by HASJ** [comment]
I thought the same thing but I don't have the skills to fix it.

**Comment by loopuleasa** [comment]
just go into the autoexec.cfg and the last line should be the dota_remap_alt

place the key between the " " as the key you want

**Comment by HASJ** [comment]
Thanks!
