### ISSUE TITLE
Follow does not work correctly

### ISSUE THREAD

**Issue by Elliotw44** [loopuleasa/Dota2-TheCore-Config-Engine#61]
When you issue a unit to follow your hero. The unit will just walk to you hero then stop following it. Example: Use helm of the dominator to gain control of a jungle creep. Now try to have the jungle creep follow you.

**Comment by loopuleasa** [comment]
That's usually because of right click deny activated.

You need to use the Space+A I think, for the follow command. Normal right click doesn't work.

**Comment by Elliotw44** [comment]
yes that is correct
