### ISSUE TITLE
Is there a way to use the standard ctrl+click player portrait for missing/returned?

### ISSUE THREAD

**Issue by tgfish** [loopuleasa/Dota2-TheCore-Config-Engine#62]
Clearly as CTRL is a key modifier we can't do that, any way to use another key?

**Comment by loopuleasa** [comment]
Unsure if you can rebind CTRL to another key like I did with ALT.
It needs a special command.

**Comment by tgfish** [comment]
I would be happy with any key as long as I could do "Mapped key" + Hero Portrait Left Click to message the team "X hero missing" "X hero returned".

**Comment by loopuleasa** [comment]
That is tied to the CTRL key only I think, and cannot be rebound afaik.

**Comment by mfarrugi** [comment]
With <kbd>ALT</kbd> remapped to  <kbd>` </kbd> , most alt-clicking functionality sticks with alt, except for the portrait shortcuts.   
X pings are difficult as well, since <kbd> CTRL + `</kbd> + Click is generally a pain to use.

Is it possible to change it to be more consistent / less painful?

**Comment by leodag** [comment]
No, the inconsistencies are caused by sloppy implementation of ALT remapping by valve, no config can change the cases where it still uses ALT

**Comment by loopuleasa** [comment]
Yeah...

I ranted a lot on the Volvo dev forums. We can't really FULLY remap these without external scripts:
- left click
- right click
- middle click
- shift
- ctrl
- alt (partially, has bugs with type-to-chat-on-alt-click functions)
