### ISSUE TITLE
Ping not working in Reborn

### ISSUE THREAD

**Issue by Jackeywhip** [loopuleasa/Dota2-TheCore-Config-Engine#65]
Hi,
thanks a lot for the config, I've been using it for almost a year and I am more than satisfied with it. However, when I use your config for Reborn I cannot use ping. It does not matter if I use Alt or Tilde, it still does not do the ping.

**Comment by loopuleasa** [comment]
Make sure your keyboard is default.

What key happens when you press tilde?

it should be this: `

If not, change it in the autoexec.cfg file at the end to what key is there

**Comment by Jackeywhip** [comment]
When I press tilde this happens ";".
However, in normal Dota, not Reborn, the config in autoexec is dota_remap_alt_key "`" and it is working. In Reborn it is the same and it is not working.

**Comment by CharlyCheater** [comment]
For me (german keyboard) I had to change dota_remap_alt_key to "CARET".
They seem to have changed some things. To check for yourself you should go to the ingame settings and set the keybind for Console or anything else to your desired key.
Then close the game, open the user_keys_slot0.vcfg and there you should see how you can address the key for yourself.

**Comment by Jackeywhip** [comment]
This was indeed the problem. On my Czech keyboard it was "SEMICOLON". Thanks a lot!

**Comment by loopuleasa** [comment]
CARET?

Hmm, that might be it.
