### ISSUE TITLE
Normal-cast not working correctly in Source1 

### ISSUE THREAD

**Issue by TakeAwayRobin** [loopuleasa/Dota2-TheCore-Config-Engine#67]
In Reborn, the config engine works beautifully and i have no problems.

That said, in Source1 for some reason the Space-bar normalcast only seems to work for items, but not abilities. I haven't changed anything within the Source1 config in ages so I don't know why it would glitch now. I've tried using the f7 toggle to reset it, as well as reloading the engine entirely but to no avail. It's not a huge issue, as I prefer playing in Reborn anyways but I thought I'd run it by you anyways. Thanks m8.

**Comment by Jackeywhip** [comment]
Do you have everything unbinded in ingame Dota settings?

**Comment by Sembrani** [comment]
Can be closed, source 1 has been depreciated.
