### ISSUE TITLE
Autoexec not loading automatically on Dota Reborn start

### ISSUE THREAD

**Issue by loopuleasa** [loopuleasa/Dota2-TheCore-Config-Engine#68]
This might be an issue to some people because volvo overwrites the game_convars.vcfg file on some updates.
Just replace it and it should work (or alternatively just type in console "exec autoexec.cfg")

**Comment by Sembrani** [comment]
shouldn't be a problem anymore since autoexec.cfg works without the game_convars.vcfg file modified now.

Issue can be closed
