### ISSUE TITLE
Mini map hero icons dont resize

### ISSUE THREAD

**Issue by Elliotw44** [loopuleasa/Dota2-TheCore-Config-Engine#74]
When heroes on the mini map get close together their icons don't rezise. this causes lots of overlap and you cant tell much from the mini map when heroes bunch up.

**Comment by loopuleasa** [comment]
They don't resize in Hero Icon mode (because of valve reasons). They only resize in colored arrow mode.

Press ALT or TILDE or whatever you use when some heroes are bunched up and you'll see it work.

I wish it could be implemented for items too.

**Comment by Elliotw44** [comment]
dat sucks T_T
