### ISSUE TITLE
Potential New Feature? -- Hero mode switch script

### ISSUE THREAD

**Issue by Sembrani** [loopuleasa/Dota2-TheCore-Config-Engine#87]
Not sure if you want to include this in this project, but I made a  set of config file for selecting and loading binds for individual heroes without having to open the console. Not sure how useful this will be in practice, but it's there.

https://github.com/Sembrani/D2HeroKeys

**Comment by loopuleasa** [comment]
For selecting too?

So you basically press a key and your keyboard switches into hero switching mode, then you have preset keys for heroes X Y Z. Like Q being meepo, W being ember, and so on?

If that's the case, I think that's too particular. Ideally the perfect implementation we can't make is have a guy with a search box to appear to type hero name, then you press enter.

Closest one is the hero custom mode I've setup, that requires console run.

**Comment by Sembrani** [comment]
The keys you press for selecting the hero are you typing the name of the hero, some heroes only need 1 keypress, others require a few...

**Comment by loopuleasa** [comment]
like:

Key_Shift -> A -> L -> C

turns into alchemists binds and then it shows a say_student message that it loaded?

If that's the case, it seems fast and useful for the main cfg engine too.

Is this switching functionality implemented for all heroes?

**Comment by Sembrani** [comment]
it's not a key-shift, it's a toggle, but yes, that's how it works. So the toggle remains selected until a hero is selected, or F1 is pressed, to cancel the hero selection.

**Comment by loopuleasa** [comment]
I love it. Fairly ingenious and more user friendly, especially if it prints in student chat.

I would love to have it on the super compact layout, integrated or replacing the current hero modes in place (with split functionality of ALT, SPACE, DEFAULT). 

I would love it bound to an F key and I think double pressing it should remove binds (nohero mode)

**Comment by Sembrani** [comment]
I already have a branch which can be copied over the super compact binds, and is bound to "p", so it would only need a few minor changes after that. Looking at the keybinds, all the F-keys are already bound, unless you use a modifier layer, and I'm not too sure how well that would work.

**Comment by Sembrani** [comment]
Just let me know what key you want it bound to, and any other keys that need to be rebound around it and I should be able to have it done fairly quickly.

**Comment by loopuleasa** [comment]
I have a few ideas for the F keys to make them more usable:

- Toggle combat log on F10
- Toggle auto select summons on Space-F5
- Toggle select hero mode (new) on F6
- I would also like SPACE+F2 to jump to courier (new), to make it consistent with other things
- Take from stash on SPACE+Y
And the visual layouts should be modified with the changes.

This toggle should be on a far to reach key, because of the trigger frequency.

On the side, I haven't tested new version. Is SPACE+H the scoreboard and SPACE+Tab cycle jump correctly?

Note is that Space+Y was unused.

**Comment by loopuleasa** [comment]
These changes should be traced to notify changes for then ext changelog

**Comment by loopuleasa** [comment]
Another idea I had is if there is a way to make F5 enable/disable switch the in-game menu.
It only enables menu now.

**Comment by Sembrani** [comment]
Yes, SPACE+H for scoreboard works well, but I can't say anything for SPACE+Tab

**Comment by loopuleasa** [comment]
Awesome. Testing it right now.

I'll handle the visual layout keybinds later on.

**Comment by loopuleasa** [comment]
Alright, I cleaned stuff up, done some testing and added everything to https://github.com/loopuleasa/Dota2-TheCore-Config-Engine/issues/26

**Comment by loopuleasa** [comment]
Good job.

**Comment by Sembrani** [comment]
Thanks for the reminder. will get onto that pretty soon.
