### ISSUE TITLE
Deleting Legacy binds?

### ISSUE THREAD

**Issue by Sembrani** [loopuleasa/Dota2-TheCore-Config-Engine#93]
Since everyone is on reborn now (and have been for a while), I think it would be a good idea to remove the legacy layouts since there is no longer any need for them, and their presence would only confuse some people.

**Comment by loopuleasa** [comment]
I do agree, but I think we need to make a folder called "Archive" instead and add it inside that, layered and out of reach.

We also have to update the readmes to be particular to Reborn.

**Comment by dodekeract** [comment]
Alternatives to an archive folder:
- Just delete the config (git will save it and you can browse old commits)
- Move the config to a different branch (might be the best solution)

**Comment by loopuleasa** [comment]
I think any of the 3 options is viable and better than leaving them lying around.

**Comment by don4of4** [comment]
Since it's not possible to create a pull request to create an upstream branch, I would probably recommend just deleting the legacy folder per @dodekeract's suggestion.
