### ISSUE TITLE
dota_unit_allow_moveto_direction has been removed.

### ISSUE THREAD

**Issue by jaccarmac** [loopuleasa/Dota2-TheCore-Config-Engine#96]
From the patchnotes: `Replaced dota_unit_allow_moveto_direction with +dota_unit_movetodirection which can now be bound to a key`. I am working on a patch as we speak.

**Comment by loopuleasa** [comment]
so it basically becomes "Press a key to move at direction?" or "Have this key pressed, and move commands go in a straight line"

**Comment by jaccarmac** [comment]
The second. It's a mode that can be toggled. The old behavior got restored, though, so I just replaced the name of the command in the end. No hacks necessary!
