### ISSUE TITLE
LICENSE?

### ISSUE THREAD

**Issue by dodekeract** [loopuleasa/Dota2-TheCore-Config-Engine#98]
It would be nice if you could include a LICENSE.md file (consider MIT license or chose anything you want).

**Comment by loopuleasa** [comment]
why would we need a LICENSE.md file?

**Comment by dodekeract** [comment]
Because you're technically publishing code and this would explain how this code can be modified and used. If you don't specify a license this technically means that nobody else is allowed to modify, re-distribute or in some cases even use this. If you chose a license for this code it will be clear to everybody involved what is allowed to be done and what is prohibited. Also most licenses include a "liability disclaimer", which prevents you from ever being responsible for things your code does wrong.

(for usual software this would mean if a bug in your software deletes files which have a huge worth for some company it would not be the developer's fault and the developer can't be sued; In your case I can't imagine anything except "I lost tournament X due to bug Y in your config, now give me my money", which I don't even know if it would be legal to claim that, but whatever)

In case you have no idea which license fits what you're intending to allow, here is a useful comparison:
http://choosealicense.com/licenses/

This page also shows you what I was talking about as you're currently using some sort of "no license" approach, which **forbids distribution, modification and sublicensing**.

In my opinion your projects fits the MIT license the most, since it's one of the least complicated ones and widely spread and allows nearly everything.

**Comment by loopuleasa** [comment]
I find these legal stuff as overhead and not that important.

As far as I am concerned, and the github coding philosophy supports, this engine and all the scripting code that have been done are Open Source.

**Comment by dodekeract** [comment]
Since #131 got merged, I will close this.
